language: generic
# here sudo means require super permission to do some thing. 
sudo: required

#Travis only have our code not docker which is we need to create a image
# Ask for docker first
services:
    - Docker

#before doing any thing means running test we need to build our image
#So use this command  
#here giving name to our image but we are not doing any think only travis will do internally  
before_install:
    - docker build -t amitumrikar:docker-react -f Dockerfile.dev .

# use to give command to run the docker image that we create and run test.
script:
    - docker run -e CI=true amitumrikar:docker-react npm run test